# Generated by Django 5.0.6 on 2025-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_codesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript')], default='python', max_length=50),
        ),
    ]
